steps:
  # Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]

# Docker Build
- name: 'Bild'
  args: ['build', '-t',
         'us-central1-docker.pkg.dev/${PROJECT_ID}/apiimage/image:${SHORT_SHA}', '.']

# Docker push to Google Artifact Registry
- name: 'Push to artifact'
  args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/apiimage/image']

# Deploy to Cloud Run
- name: Deploy to cloud run
  args: [ 'gcloud', 'run', 'deploy', 'techbricksapi',
          '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/apiimage/image:${SHORT_SHA}',
          '--region', 'us-central1', '--platform', 'managed',
          '--allow-unauthenticated' ,'--update-env-vars', 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}']